// Generated by CoffeeScript 1.3.3
(function() {
  var Mat, VideoCapture, cv, testCapture;

  cv = require('./opencv');

  VideoCapture = cv.VideoCapture;

  Mat = cv.Mat;

  testCapture = function() {
    var cap, edges, frame, running, _results;
    cap = new VideoCapture(0);
    if (!cap.isOpened()) {
      console.log('Could not open video device');
      return;
    }
    edges = new Mat;
    cv.namedWindow("camera", 1);
    cv.namedWindow("output", 1);
    running = true;
    _results = [];
    while (running) {
      frame = new Mat;
      cap.read(frame);
      cv.imshow("camera", frame);
      cv.cvtColor(frame, edges, cv.CV_BGR2GRAY);
      cv.imshow("output", edges);
      if (cv.waitKey(27) >= 0) {
        _results.push(running = false);
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  testCapture();

}).call(this);
