// Generated by CoffeeScript 1.3.3
(function() {
  var Mat, cv, opencvjs, _;

  opencvjs = require('../build/Debug/addon.node');

  _ = require('underscore');

  cv = opencvjs.OpenCV;

  Mat = opencvjs.Mat;

  _.extend(module.exports, opencvjs);

  delete module.exports.OpenCV;

  _.extend(module.exports, opencvjs.OpenCV);

}).call(this);
