// Generated by CoffeeScript 1.3.3
(function() {
  var cv, plane, src;

  cv = require('./opencv');

  src = cv.imread('scripts/test.jpg', 1);

  console.log(src.channels);

  plane = [];

  cv.split(src, plane);

  console.log(plane);

}).call(this);
