// Generated by CoffeeScript 1.3.3
(function() {
  var cv, fileName, path, plane, src;

  cv = require('./opencv');

  path = require('path');

  fileName = path.resolve('../scripts/test.jpg');

  console.log(fileName);

  src = cv.imread(fileName, 1);

  console.log(src.channels);

  plane = [];

  cv.split(src, plane);

  console.log(plane);

}).call(this);
